# Generated by Django 2.2.2 on 2019-06-21 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=40)),
                ('modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=40)),
                ('owned', models.DateField()),
                ('owned_prev', models.CharField(max_length=40)),
                ('assigned', models.DateField(blank=True, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('fact_date', models.DateField(blank=True, null=True)),
                ('des', models.TextField(blank=True, max_length=1000, null=True)),
                ('result', models.TextField(blank=True, max_length=1000, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='activity_assigned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Activity')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.activity',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=40)),
                ('modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=40)),
                ('owned', models.DateField()),
                ('owned_prev', models.CharField(max_length=40)),
                ('assigned', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'In progress'), ('F', 'Finished')], max_length=6)),
                ('shipDatePlanned', models.DateField(blank=True, null=True)),
                ('shipDateFact', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='client_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_client_fk', to='crm.Client'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owned_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Client')),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=40)),
                ('modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=40)),
                ('owned', models.DateField()),
                ('owned_prev', models.CharField(max_length=40)),
                ('assigned', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.client', models.Model),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Client')),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=40)),
                ('modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=40)),
                ('owned', models.DateField()),
                ('owned_prev', models.CharField(max_length=40)),
                ('assigned', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lead_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.client', models.Model),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Client')),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=40)),
                ('modified', models.DateField(auto_now=True)),
                ('modified_by', models.CharField(max_length=40)),
                ('owned', models.DateField()),
                ('owned_prev', models.CharField(max_length=40)),
                ('assigned', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='individual_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.client', models.Model),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Activity')),
                ('type', models.CharField(choices=[('E', 'E-mail'), ('C', 'Call'), ('V', 'Visit')], max_length=6)),
                ('direction', models.IntegerField(choices=[(0, 'Incoming'), (1, 'Outgoing')], default=1)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'In progress'), ('F', 'Finished')], default='N', max_length=6)),
                ('deal_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Deal')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm.activity',),
        ),
    ]
