# Generated by Django 2.2.2 on 2019-06-21 23:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='created',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='owned_prev',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owned_prev',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='owned_prev',
        ),
        migrations.AddField(
            model_name='client',
            name='assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='client_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.CharField(default='Admin', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='modified_by',
            field=models.CharField(default='Admin', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='owned',
            field=models.DateField(default=datetime.datetime(
                2019, 6, 21, 23, 15, 21, 171513, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='owned_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='client_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='owned_prev',
            field=models.CharField(default='Admin', max_length=40),
            preserve_default=False,
        ),
    ]
