# Generated by Django 2.2.2 on 2019-06-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190622_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In progress'), ('F', 'Finished')], default='N', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.Client'),
            preserve_default=False,
        ),
    ]
