# Generated by Django 2.2.2 on 2019-06-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190622_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owned_prev',
        ),
        migrations.AddField(
            model_name='order',
            name='activity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Activity'),
            preserve_default=False,
        ),
    ]
