# Generated by Django 2.2.2 on 2019-06-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190624_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipDateFact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipDatePlanned',
        ),
        migrations.AlterField(
            model_name='activity',
            name='client_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_client_fk', to='crm.Client'),
        ),
    ]
