# Generated by Django 2.2.5 on 2019-10-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190920_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='deal_fk',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_rel',
            field=models.ManyToManyField(related_name='_activity_activity_rel_+', to='crm.Activity'),
        ),
    ]
